# Generated by Django 4.2.3 on 2023-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
